In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [ ]:
import warnings
warnings.filterwarnings("ignore")
sns.set(style="whitegrid")

In [3]:
df=pd.read_csv("AIML Dataset.csv")

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.columns

In [ ]:
df["isFraud"].value_counts()

In [ ]:
df.isnull().sum()

In [ ]:
df.value_counts("type").plot(kind="bar",title="transactiontype",color="red")
plt.xlabel("transaction type")
plt.ylabel("count")
plt.show()

In [ ]:
fraudrate=df.groupby("type")["isFraud"].mean().sort_values(ascending=False)
fraudrate.plot(kind="bar",color="red",title="fraud rate")
plt.xlabel("transaction type")
plt.show()

In [ ]:
df["amount"].describe().astype(int)

In [ ]:
sns.histplot(np.log1p(df["amount"]),bins=100,color="red",kde=True)
plt.xlabel("Log of Amount")
plt.ylabel("Frequency")
plt.title("Distribution of Transaction Amounts")
plt.show()

In [ ]:
sns.boxplot(data=df[df["amount"]< 50000], x="isFraud", y="amount", palette="Set2" )
plt.show()

In [ ]:
df.columns

In [ ]:
df["balancedifferoriginal"]=df["oldbalanceOrg"]-df["newbalanceOrig"]
df["balancedifferdesti"]=df["newbalanceDest"]-df["oldbalanceDest"]

In [ ]:
(df["balancedifferoriginal"] < 0).sum()

In [ ]:
frauds_per_step=df[df["isFraud"] == 1]["step"].value_counts().sort_index()
sns.lineplot(x=frauds_per_step.index,y=frauds_per_step.values,color="red")
plt.show()

In [ ]:
top_senders=df["nameOrig"].value_counts().head(5)
top_receievers=df["nameDest"].value_counts().head(5)
sns.barplot(x=top_senders.index,y=top_senders.values,color="red")
plt.show()

In [ ]:
fraud_users=df[df["isFraud"]==1]["nameOrig"].value_counts().head(5)

In [ ]:
fraud_users

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV

In [4]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [5]:
df_model=df.drop(["step","nameOrig","nameDest","isFlaggedFraud"],axis=1)

In [6]:
df_model.head()

,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
0,PAYMENT,9839.64,170136.0,160296.36,0.0,0.0,0
1,PAYMENT,1864.28,21249.0,19384.72,0.0,0.0,0
2,TRANSFER,181.00,181.0,0.00,0.0,0.0,1
3,CASH_OUT,181.00,181.0,0.00,21182.0,0.0,1
4,PAYMENT,11668.14,41554.0,29885.86,0.0,0.0,0

In [6]:
catogorical=['type']
numerical=["amount","oldbalanceOrg","newbalanceOrig","oldbalanceDest","newbalanceDest"]

In [7]:
y=df_model["isFraud"]
X=df_model.drop("isFraud",axis=1)

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,stratify=y)

In [9]:
preprocessor=ColumnTransformer(
    transformers=[("nums",StandardScaler(),numerical),("cata",OneHotEncoder(drop="first"),catogorical)],remainder="drop"
)

In [15]:
model=XGBClassifier(tree_method="hist",scale_pos_weight=10)
param_grid = {
    'model__max_depth': [3, 5, 7],
    'model__learning_rate': [0.01, 0.1, 0.2],
    'model__n_estimators': [100, 200, 300]
}

In [16]:
best_pipeline=Pipeline(steps=[("preprocessor",preprocessor),("model",model)])
pipeline=RandomizedSearchCV(estimator=best_pipeline,param_distributions=param_grid, cv=3,n_jobs=-1,n_iter=10,random_state=42)
pipeline.fit(X_train,y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('nums',
                                                                               StandardScaler(),
                                                                               ['amount',
                                                                                'oldbalanceOrg',
                                                                                'newbalanceOrig',
                                                                                'oldbalanceDest',
                                                                                'newbalanceDest']),
                                                                              ('cata',
                                                                               OneHotEncoder(drop='first'),
                                                                               ['type'])])),
                                             ('model',
                                              XGBClassifier(base_score=None,
                                                            booster=None,
                                                            callbacks=None,
                                                            colsample_bylevel=None,
                                                            colsample...
                                                            max_cat_to_onehot=None,
                                                            max_delta_step=None,
                                                            max_depth=None,
                                                            max_leaves=None,
                                                            min_child_weight=None,
                                                            missing=nan,
                                                            monotone_constraints=None,
                                                            multi_strategy=None,
                                                            n_estimators=None,
                                                            n_jobs=None,
                                                            num_parallel_tree=None, ...))]),
                   n_jobs=-1,
                   param_distributions={'model__learning_rate': [0.01, 0.1,
                                                                 0.2],
                                        'model__max_depth': [3, 5, 7],
                                        'model__n_estimators': [100, 200, 300]},
                   random_state=42)

In [17]:
best_pipeline=pipeline.best_estimator_

In [18]:
y_predict=best_pipeline.predict(X_test)
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1906322
           1       0.90      0.78      0.84      2464

    accuracy                           1.00   1908786
   macro avg       0.95      0.89      0.92   1908786
weighted avg       1.00      1.00      1.00   1908786

In [19]:
confusion_matrix(y_test,y_predict)

array([[1906105,     217],
       [    541,    1923]])

In [20]:
pipeline.score(X_test,y_test)

0.9996028889566457

In [21]:
import joblib
joblib.dump(pipeline,"fraud_detection_model_XGBOOST.pkl")

['fraud_detection_model_XGBOOST.pkl']

In [ ]:
X.columns